name: Tests

on:
  workflow_dispatch: {}
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup spack
      uses: spack/setup-spack@v2.1.1
      with:
        ref: develop

    - name: Install MPI
      run: |
        sudo apt install -y libmpich-dev

    - name: Find external packages
      run: |
        spack -e . external find --not-buildable cmake
        spack -e . external find --not-buildable perl
        spack -e . external find --not-buildable mpich

    - name: Add mochi-spack-packages
      run: |
        git clone https://github.com/mochi-hpc/mochi-spack-packages /opt/spack/mochi-spack-packages
        spack -e . repo add /opt/spack/mochi-spack-packages

    - name: Install spack environment
      run: |
        spack -e . concretize -f
        spack -e . install

    - name: Show spack-installed packages for debugging
      run: |
        spack -e . find -dlv

    - name: Hack to make na+sm work
      run: |
        sudo /usr/sbin/sysctl kernel.yama.ptrace_scope=0

    - name: Build code run unit tests
      run: |
        eval `spack env activate --sh .` &&
        ./prepare.sh &&
        ./configure --prefix=`pwd` &&
        make check

    - name: Show logs
      if: failure()
      run: |
        cat tests/*.log
